### ISSUE TITLE
Can't delete item

### ISSUE THREAD

**Issue by reneelynn** [SpiderOak/Encryptr#234]
If an entry only has an item name and no other information it can neither be edited nor deleted.
2.0.0 RC.13 (Win, rpm)

**Comment by reneelynn** [comment]
![screen shot 2015-11-23 at 1 36 02 pm](https://cloud.githubusercontent.com/assets/3867179/11345809/7154096c-91e7-11e5-9578-87eed3604cdc.png)

**Comment by devgeeks** [comment]
Oh neat.

I know why... I'll see if I can come up with an easy fix.

**Comment by devgeeks** [comment]
This should be fixed in 140ee07b1287b3df57f8ce84f6e90fab570df915

**Comment by salvor7** [comment]
I'm still getting this issue. I can't delete from the mobile app either. 

![image](https://cloud.githubusercontent.com/assets/5132080/23591628/109f13fa-01a8-11e7-847f-24663f6e03d1.png)

**Comment by AntoineTurmel** [comment]
Could be linked to issue #247

**Comment by caj411** [comment]
I have the same problem, its been like this for several years.  I have an item I want to delete but can't, it never loads, it just continues to try to load ad infinium. I don't get an error message, but it never loads and I can't delete the entry.   I'm using the Linux desktop application.
![54](https://user-images.githubusercontent.com/34217875/35188385-fbc1da86-fdf9-11e7-85b1-0a7b41636ea1.png)

**Comment by ghost** [comment]
I can confirm this is still happening as of today.

It is occurring on both the Android and Windows 10 clients.

**Comment by caj411** [comment]
I use Linux, so you can add Linux clients too. 

-- 
 Securely sent with Tutanota. Claim your encrypted mailbox today! 
 https://tutanota.com


May 19, 2018, 6:20 PM by notifications@github.com:

**Comment by fancsali** [comment]
Apologies, but still happening both on Android and Mac. I've got an entry that is loading forever.
